spring:
  datasource:
    url: jdbc:mysql://localhost:3306/permission
    username: root
    password: xqb19971024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
#  session:
#    store-type: redis
#  redis:
#    host: wxseller.club
#    port: 6379
server:
  port: 8080